// cli/src/integrations/adapters/wrapper-mode.ts
//
// Wave 11B + 11B.5 — Shared factory for wrapper-mode connector adapters.

import { execFileSync } from 'node:child_process';
import { openSync, readSync, closeSync } from 'node:fs';
import { resolve, join } from 'node:path';
import { platform } from 'node:os';
import { lstat, open as fsOpen } from 'node:fs/promises';
import { resolveHiveHome } from '../../shared/index.js';
import type { HostCli } from '../../statusline/types.js';
import type {
  AdapterTarget,
  AdapterCtx,
  ConnectorAdapter,
  InstallResult,
  UninstallResult,
} from './types.js';
import { writeWrapper } from '../wrapper-driver.js';
import { writeMarker, readMarker, removeMarker } from '../integration-marker.js';
import {
  safeUnlinkInHiveFlow,
  safeUnlinkInUserCache,
} from '../../statusline/storage.js';

const WRAPPER_MARKER = 'AUTO-GENERATED by hive-flow wrapper-driver';
const OWNERSHIP_MAX_BYTES = 512;

export interface WrapperModeConfig {
  readonly target: AdapterTarget;
  readonly hostCli: HostCli;
  readonly hostBin: string;
}

async function isHiveFlowWrapper(filePath: string): Promise<boolean> {
  try {
    const fh = await fsOpen(filePath, 'r');
    try {
      const buf = Buffer.alloc(OWNERSHIP_MAX_BYTES);
      const { bytesRead } = await fh.read(buf, 0, OWNERSHIP_MAX_BYTES, 0);
      return buf.subarray(0, bytesRead).toString('utf8').includes(WRAPPER_MARKER);
    } finally {
      await fh.close();
    }
  } catch {
    return false;
  }
}

function resolveHostBin(
  bin: string,
  skipPath: string,
): string | undefined {
  try {
    const isWin = platform() === 'win32';
    const cmd = isWin ? 'where' : 'which';
    const args = isWin ? [bin] : ['-a', bin];
    const output = execFileSync(cmd, args, { encoding: 'utf8' }).trim();
    const candidates = output.split('\n').map((s) => s.trim()).filter(Boolean);

    for (const candidate of candidates) {
      if (resolve(candidate) === resolve(skipPath)) continue;
      let isWrapper = false;
      try {
        const fd = openSync(candidate, 'r');
        try {
          const buf = Buffer.alloc(OWNERSHIP_MAX_BYTES);
          const n = readSync(fd, buf, 0, OWNERSHIP_MAX_BYTES, 0);
          isWrapper = buf.subarray(0, n).toString('utf8').includes(WRAPPER_MARKER);
        } finally {
          closeSync(fd);
        }
      } catch {
        continue;
      }
      if (isWrapper) continue;
      return candidate;
    }
    return undefined;
  } catch {
    return undefined;
  }
}

function wrapperDir(ctx: AdapterCtx): string {
  if (ctx.scope === 'user') {
    return join(resolveHiveHome().home, 'bin');
  }
  return join(ctx.projectRoot, '.hive-flow', 'bin');
}

function wrapperFileName(hostBin: string): string {
  return platform() === 'win32' ? `${hostBin}.cmd` : hostBin;
}

function userCacheBase(): string {
  return resolveHiveHome().home;
}

export function createWrapperModeAdapter(config: WrapperModeConfig): ConnectorAdapter {
  const { target, hostCli, hostBin } = config;

  return {
    target,
    tier: 'wrapper-mode' as const,

    async install(ctx: AdapterCtx): Promise<InstallResult> {
      const dir = wrapperDir(ctx);
      const destPath = join(dir, wrapperFileName(hostBin));
      const baseDir = ctx.scope === 'user' ? userCacheBase() : ctx.projectRoot;

      const realBin = resolveHostBin(hostBin, destPath);
      if (!realBin) {
        return { wrote: [], skipped: [`${hostBin}: no non-Hive-Flow host binary found on PATH`] };
      }

      if (ctx.dryRun) {
        return { wrote: [destPath], skipped: [] };
      }

      // Gate 1: don't overwrite user-owned files
      try {
        await lstat(destPath);
        const marker = await readMarker({ projectRoot: ctx.projectRoot, target, scope: ctx.scope });
        const markerOwns = marker?.scriptPath === destPath;
        const bodyOwned = await isHiveFlowWrapper(destPath);
        if (!markerOwns || !bodyOwned) {
          throw new Error(
            `Conflict: ${destPath} already exists and is not a Hive Flow-owned wrapper for ${target}/${ctx.scope}. ` +
            `Remove or rename the file before installing.`,
          );
        }
      } catch (e: unknown) {
        if ((e as NodeJS.ErrnoException).code === 'ENOENT') {
          // File absent — safe to create
        } else if (e instanceof Error && e.message.startsWith('Conflict:')) {
          throw e;
        } else {
          throw e;
        }
      }

      await writeWrapper({
        realCliBin: realBin,
        hostCli,
        hiveFlowCli: ctx.cliBin,
        destPath,
        baseDir,
        ...(ctx.scope === 'project' ? { projectRoot: ctx.projectRoot } : {}),
      });

      await writeMarker({
        projectRoot: ctx.projectRoot,
        target,
        tier: 'wrapper-mode',
        scope: ctx.scope,
        scriptPath: destPath,
        realCliBin: realBin,
      });

      return {
        wrote: [destPath],
        skipped: [],
      };
    },

    async uninstall(ctx: AdapterCtx): Promise<UninstallResult> {
      const marker = await readMarker({
        projectRoot: ctx.projectRoot,
        target,
        scope: ctx.scope,
      });

      if (!marker) {
        return { removed: [] };
      }

      const removed: string[] = [];

      // Gate 3: recompute canonical path — don't trust marker.scriptPath
      const dir = wrapperDir(ctx);
      const canonicalDest = join(dir, wrapperFileName(hostBin));

      if (!ctx.dryRun) {
        if (ctx.scope === 'project') {
          await safeUnlinkInHiveFlow(canonicalDest);
        } else {
          await safeUnlinkInUserCache(canonicalDest, userCacheBase());
        }
        removed.push(canonicalDest);
      } else {
        removed.push(canonicalDest);
      }

      if (!ctx.dryRun) {
        await removeMarker({
          projectRoot: ctx.projectRoot,
          target,
          scope: ctx.scope,
        });
      }

      return { removed };
    },
  };
}
