// v3/@hive-flow/cli/src/integrations/launcher.ts
import { mkdir, chmod, readFile } from 'node:fs/promises';
import { atomicWrite } from './atomic-merge.js';
import { dirname, resolve } from 'node:path';

/**
 * Write a POSIX shim that execs the real MCP server entrypoint.
 *
 * Bug-fix vs prior runbooks:
 *  - Use printf with %q-style quoting via Node-built single-quote escaping so paths
 *    containing spaces OR double-quotes are safe.
 *  - Generate a bash shim that exec's `node <entrypoint>`, NOT an ES-module `import` shim
 *    under `#!/usr/bin/env node` — Codex's import-shim would throw `Cannot use import statement
 *    outside a module` without `"type": "module"` in nearest package.json. The bash shim
 *    avoids that class of failure entirely and works without any package.json gymnastics.
 *  - Refuse paths with control characters as a defense-in-depth measure.
 */
export async function writeStableLauncher(path: string, mcpServerEntrypoint: string): Promise<void> {
  if (/[\x00-\x1f]/.test(mcpServerEntrypoint)) {
    throw new Error(`MCP server path contains control characters: ${JSON.stringify(mcpServerEntrypoint)}`);
  }
  await mkdir(dirname(path), { recursive: true });
  // Single-quoted bash: only single-quote needs escaping (close, escape, reopen)
  const quoted = "'" + mcpServerEntrypoint.replace(/'/g, "'\\''") + "'";
  const shim = `#!/usr/bin/env bash
# AUTO-GENERATED by 'hive-flow setup'. Do not edit by hand.
# Regenerate with: hive-flow setup reconcile
exec node ${quoted} "$@"
`;
  // Only rewrite if changed (idempotent)
  let current: string | null = null;
  try { current = await readFile(path, 'utf8'); } catch {}
  if (current !== shim) {
    await atomicWrite(path, shim);
    await chmod(path, 0o755); // belt-and-suspenders
  }
}

export function resolveLauncherPath(scope: 'user' | 'project', homeDir: string, projectRoot: string): string {
  if (scope === 'user') return resolve(homeDir, '.hive-flow', 'bin', 'hive-flow-mcp-server');
  return resolve(projectRoot, '.hive-flow', 'bin', 'hive-flow-mcp-server');
}

export function hiveFlowMcpEnv(): Record<string, string> {
  // NEW DIRECTIVE: 50 working agents + 10 queue depth. Hard cap = 60. Was 15.
  return {
    HIVE_FLOW_MODE: 'v3',
    HIVE_FLOW_HOOKS_ENABLED: 'true',
    HIVE_FLOW_TOPOLOGY: 'hierarchical-mesh',
    HIVE_FLOW_MAX_AGENTS: '50',                  // max working (actively executing) agents
    HIVE_FLOW_AGENT_QUEUE_DEPTH: '10',           // max queued (waiting to execute) agents; hard cap = MAX + QUEUE_DEPTH = 60
    HIVE_FLOW_AGENT_QUEUE_REJECT_ABOVE: 'true',  // when working=50 AND queue=10, reject new requests with busy:queue-full
    HIVE_FLOW_MEMORY_BACKEND: 'hybrid',
  };
}
