// v3/@hive-flow/cli/src/integrations/launcher.ts
import { existsSync } from 'node:fs';
import { mkdir, chmod, readFile } from 'node:fs/promises';
import { atomicWrite } from './atomic-merge.js';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * POSIX single-quote escaping for embedding a path into a bash single-quoted
 * literal. Refuses control characters as a defense-in-depth measure so that
 * NUL/CR/LF in attacker-supplied paths cannot break out of the literal or
 * inject newlines into the generated shim.
 *
 * Output is always wrapped in single quotes, and any embedded single quote
 * is encoded with the standard close/escape/reopen pattern (`'\''`).
 *
 * Shared by writeStableLauncher (MCP shim) and writeStableStatuslineLauncher
 * (statusline shim) so both launchers escape paths identically.
 */
function shellQuote(value: string): string {
  if (/[\x00-\x1f]/.test(value)) {
    throw new Error(`Path contains control characters: ${JSON.stringify(value)}`);
  }
  return "'" + value.replace(/'/g, "'\\''") + "'";
}

/**
 * Write a POSIX shim that execs the real MCP server entrypoint.
 *
 * Bug-fix vs prior runbooks:
 *  - Use printf with %q-style quoting via Node-built single-quote escaping so paths
 *    containing spaces OR double-quotes are safe.
 *  - Generate a bash shim that exec's `node <entrypoint>`, NOT an ES-module `import` shim
 *    under `#!/usr/bin/env node` — Codex's import-shim would throw `Cannot use import statement
 *    outside a module` without `"type": "module"` in nearest package.json. The bash shim
 *    avoids that class of failure entirely and works without any package.json gymnastics.
 *  - Refuse paths with control characters as a defense-in-depth measure.
 */
export async function writeStableLauncher(path: string, mcpServerEntrypoint: string): Promise<void> {
  if (/[\x00-\x1f]/.test(mcpServerEntrypoint)) {
    throw new Error(`MCP server path contains control characters: ${JSON.stringify(mcpServerEntrypoint)}`);
  }
  await mkdir(dirname(path), { recursive: true });
  // Single-quoted bash: only single-quote needs escaping (close, escape, reopen)
  const quoted = shellQuote(mcpServerEntrypoint);
  const shim = `#!/usr/bin/env bash
# AUTO-GENERATED by 'hive-flow setup'. Do not edit by hand.
# Regenerate with: hive-flow setup reconcile
exec node ${quoted} "$@"
`;
  // Only rewrite if changed (idempotent)
  let current: string | null = null;
  try { current = await readFile(path, 'utf8'); } catch {}
  if (current !== shim) {
    await atomicWrite(path, shim);
    await chmod(path, 0o755); // belt-and-suspenders
  }
}

export function resolveLauncherPath(scope: 'user' | 'project', homeDir: string, projectRoot: string): string {
  if (scope === 'user') return resolve(homeDir, '.hive-flow', 'bin', 'hive-flow-mcp-server');
  return resolve(projectRoot, '.hive-flow', 'bin', 'hive-flow-mcp-server');
}

export function hiveFlowMcpEnv(): Record<string, string> {
  // NEW DIRECTIVE: 50 working agents + 10 queue depth. Hard cap = 60. Was 15.
  return {
    HIVE_FLOW_MODE: 'v3',
    HIVE_FLOW_HOOKS_ENABLED: 'true',
    HIVE_FLOW_TOPOLOGY: 'hierarchical-mesh',
    HIVE_FLOW_MAX_AGENTS: '50',                  // max working (actively executing) agents
    HIVE_FLOW_AGENT_QUEUE_DEPTH: '10',           // max queued (waiting to execute) agents; hard cap = MAX + QUEUE_DEPTH = 60
    HIVE_FLOW_AGENT_QUEUE_REJECT_ABOVE: 'true',  // when working=50 AND queue=10, reject new requests with busy:queue-full
    HIVE_FLOW_MEMORY_BACKEND: 'hybrid',
  };
}

/**
 * Resolve the runtime path to `bin/statusline.js` inside the installed (or
 * checked-out) `@hive-flow/cli` package.
 *
 * Two-strategy resolution:
 *   1. Monorepo/source layout: `<projectRoot>/v3/@hive-flow/cli/bin/statusline.js`.
 *      Used during local development and inside the hive-flow worktree.
 *   2. Installed package layout: walk up from this file's directory (compiled
 *      output lives in `dist/integrations/`, source in `src/integrations/`) up
 *      to 8 levels looking for a sibling `bin/statusline.js`. Handles both the
 *      shipped npm package and any nested `node_modules/@hive-flow/cli` install.
 *
 * Throws if neither path resolves so the caller surfaces a clear setup error
 * rather than silently writing a launcher that points at a missing file.
 */
export function resolveStatuslineRuntimeEntrypoint(projectRoot: string): string {
  // Strategy 1: monorepo/source checkout. The directory is literally named
  // `@hive-flow` then `cli`, so build it segment-by-segment to avoid any
  // shell-style expansion concerns when this path is embedded in a shim later.
  const monorepoPath = resolve(projectRoot, 'v3', '@hive-flow', 'cli', 'bin', 'statusline.js');
  if (existsSync(monorepoPath)) return monorepoPath;

  // Strategy 2: walk up from this module's directory looking for bin/statusline.js.
  // import.meta.url points at the compiled file in dist/integrations/launcher.js
  // (or src/integrations/launcher.ts during ts-node/tsx runs), so the package
  // root is typically 2 levels up; allow up to 8 to be resilient against
  // bundler-introduced nesting.
  let current = dirname(fileURLToPath(import.meta.url));
  for (let i = 0; i < 8; i++) {
    const candidate = resolve(current, 'bin', 'statusline.js');
    if (existsSync(candidate)) return candidate;
    const parent = dirname(current);
    if (parent === current) break; // hit filesystem root
    current = parent;
  }

  throw new Error('Cannot resolve @hive-flow/cli/bin/statusline.js for statusline launcher.');
}

/**
 * Resolve the on-disk path for the statusline launcher shim. Mirrors
 * `resolveLauncherPath` but for the statusline binary — kept as a separate
 * function because the filename is hardcoded inside `resolveLauncherPath`
 * (it returns `hive-flow-mcp-server`), and we never want a future refactor
 * of the MCP path to silently move the statusline launcher.
 */
export function resolveStatuslineLauncherPath(
  scope: 'user' | 'project',
  homeDir: string,
  projectRoot: string,
): string {
  if (scope === 'user') return resolve(homeDir, '.hive-flow', 'bin', 'claude-code-statusline');
  return resolve(projectRoot, '.hive-flow', 'bin', 'claude-code-statusline');
}

// REGRESSION FENCE: this launcher MUST exec bin/statusline.js. If it execs
// bin/cli.js, the heavy CLI parser, hive-flow statusline, or npx, statusline
// latency regresses by ~10x and Claude Code repaints will feel sluggish.
export async function writeStableStatuslineLauncher(
  path: string,
  statuslineEntrypoint: string,
  options: { previousCommand?: string } = {},
): Promise<void> {
  await mkdir(dirname(path), { recursive: true });
  const quoted = shellQuote(statuslineEntrypoint);
  const previousCommand = options.previousCommand ?? '';
  const quotedPreviousCommand = shellQuote(previousCommand);
  const shim = `#!/usr/bin/env bash
# AUTO-GENERATED by 'hive-flow setup'. Do not edit by hand.
# Regenerate with: hive-flow setup --auto --features statusline
set -u
HIVE_FLOW_STATUSLINE_STDIN="$(cat || true)"
HIVE_FLOW_STATUSLINE_OUTPUT="$(printf '%s' "$HIVE_FLOW_STATUSLINE_STDIN" | node ${quoted} "$@" 2>/dev/null || true)"
HIVE_FLOW_PREVIOUS_STATUSLINE_COMMAND=${quotedPreviousCommand}
HIVE_FLOW_PREVIOUS_STATUSLINE_OUTPUT=""
if [ -n "$HIVE_FLOW_PREVIOUS_STATUSLINE_COMMAND" ]; then
  HIVE_FLOW_PREVIOUS_STATUSLINE_OUTPUT="$(printf '%s' "$HIVE_FLOW_STATUSLINE_STDIN" | HIVE_FLOW_STATUSLINE_CHAINED=1 bash -lc "$HIVE_FLOW_PREVIOUS_STATUSLINE_COMMAND" 2>/dev/null || true)"
fi
if [ -n "$HIVE_FLOW_STATUSLINE_OUTPUT" ]; then
  printf '%s\\n' "$HIVE_FLOW_STATUSLINE_OUTPUT"
fi
if [ -n "$HIVE_FLOW_PREVIOUS_STATUSLINE_OUTPUT" ]; then
  printf '%s\\n' "$HIVE_FLOW_PREVIOUS_STATUSLINE_OUTPUT"
fi
`;
  // Only rewrite if changed (idempotent)
  let current: string | null = null;
  try { current = await readFile(path, 'utf8'); } catch {}
  if (current === shim) return;
  await atomicWrite(path, shim);
  await chmod(path, 0o755); // belt-and-suspenders
}

/**
 * Format a launcher path for embedding into Claude Code's `settings.json`
 * `statusLine.command` (or similar string-valued command fields). Returns a
 * shell-safe single-quoted literal so paths containing spaces, apostrophes,
 * or shell metacharacters survive intact when Claude Code spawns the shim.
 */
export function commandForClaudeSettings(launcherPath: string): string {
  return shellQuote(launcherPath);
}
