// cli/src/integrations/__tests__/wrapper-driver.test.ts
//
// Wave 11 wrapper-driver tests. Covers:
//   - POSIX template structure (no `set -e`, trap on EXIT/INT/TERM, validated
//     heartbeat regex, shell-quoted paths).
//   - Windows .cmd template structure (Node-based dispatch, CRLF endings,
//     CMD %ERRORLEVEL% propagation).
//   - `writeWrapper` symlink-safe parent creation (Wave 8.4
//     `ensureSafeUserCacheDir` integration).
//   - Permission semantics (0o755 on POSIX, irrelevant on Windows).
//   - Shell-quote round-trip for adversarial paths (spaces, apostrophes,
//     command-injection attempts via `;`).
//   - HostCli validation.
//   - HIVE_FLOW_HEARTBEAT_SECONDS validation (Wave 7.5 round-5 fork-bomb
//     hardening). NaN, zero, negative -> default; only positive integers
//     pass.

import { afterAll, beforeEach, describe, expect, it } from 'vitest';
import { mkdtemp, mkdir, readFile, stat, symlink, lstat, chmod, writeFile } from 'node:fs/promises';
import { existsSync, readFileSync } from 'node:fs';
import { tmpdir, platform } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawn, spawnSync } from 'node:child_process';
import {
  renderPosixWrapper,
  renderWindowsWrapper,
  writeWrapper,
  parseKillGraceSeconds,
} from '../wrapper-driver.js';

let dir: string;
beforeEach(async () => {
  dir = await mkdtemp(join(tmpdir(), 'hf-wrapper-'));
});

// ---------------------------------------------------------------------------
// renderPosixWrapper
// ---------------------------------------------------------------------------

describe('renderPosixWrapper', () => {
  const baseOpts = {
    realCliBin: '/opt/codex/bin/codex',
    hostCli: 'codex' as const,
    hiveFlowCli: '/usr/local/bin/hive-flow',
  };

  it('contains shebang and AUTO-GENERATED marker', () => {
    const script = renderPosixWrapper(baseOpts);
    expect(script.startsWith('#!/usr/bin/env bash\n')).toBe(true);
    expect(script).toContain('AUTO-GENERATED by hive-flow wrapper-driver');
  });

  it('contains realCliBin, hiveFlowCli, and hostCli', () => {
    const script = renderPosixWrapper(baseOpts);
    expect(script).toContain("HIVE_FLOW_REAL_CLI='/opt/codex/bin/codex'");
    expect(script).toContain("HIVE_FLOW_BIN='/usr/local/bin/hive-flow'");
    expect(script).toContain("HIVE_FLOW_HOSTCLI='codex'");
  });

  it('exports client kind for shared-core MCP/statusline routing', () => {
    const script = renderPosixWrapper(baseOpts);
    expect(script).toContain("HIVE_FLOW_CLIENT_KIND='codex'");
    expect(script).toContain('export HIVE_FLOW_CLIENT_KIND');
  });

  it('exports explicit project root when rendered for a project-scoped wrapper', () => {
    const script = renderPosixWrapper({
      ...baseOpts,
      projectRoot: '/Users/test/work/project-one',
    });
    expect(script).toContain("HIVE_FLOW_PROJECT_ROOT='/Users/test/work/project-one'");
    expect(script).toContain('export HIVE_FLOW_PROJECT_ROOT');
  });

  it('omits explicit project root when rendered for a user-scoped wrapper', () => {
    const script = renderPosixWrapper(baseOpts);
    expect(script).not.toContain('HIVE_FLOW_PROJECT_ROOT=');
  });

  it('uses `set -uo pipefail` and NOT `set -e`', () => {
    const script = renderPosixWrapper(baseOpts);
    expect(script).toContain('set -uo pipefail');
    // `set -e` standalone on its own line would abort on session-event
    // emission failures. Allow `set -uo pipefail` (which doesn't contain
    // ` -e ` as a standalone option).
    const lines = script.split('\n');
    for (const line of lines) {
      const trimmed = line.trim();
      // Reject any line that sets the `errexit` shell option in any form.
      expect(trimmed).not.toBe('set -e');
      expect(trimmed).not.toBe('set -e ');
      expect(trimmed).not.toMatch(/^set\s+-[a-z]*e[a-z]*$/);
    }
  });

  it('traps INT and TERM (signal-induced session-end)', () => {
    const script = renderPosixWrapper(baseOpts);
    // Wave 11 fix: the wrapper no longer relies on an EXIT trap because the
    // real CLI runs as a child (not via `exec`). Normal-exit session-end is
    // emitted explicitly after the child returns; signal-induced exits go
    // through the INT/TERM traps which exit with 128+signal.
    expect(script).toContain('trap hf_on_int INT');
    expect(script).toContain('trap hf_on_term TERM');
    expect(script).toContain('hf_on_int() {');
    expect(script).toContain('hf_on_term() {');
    expect(script).toContain('hf_emit_session_end() {');
  });

  it('emits session-start, session-heartbeat, session-end events', () => {
    const script = renderPosixWrapper(baseOpts);
    expect(script).toContain(
      'statusline session-start --host-cli "$HIVE_FLOW_HOSTCLI" --pid "$HIVE_FLOW_PID"',
    );
    expect(script).toContain(
      'statusline session-heartbeat --host-cli "$HIVE_FLOW_HOSTCLI" --pid "$HIVE_FLOW_PID"',
    );
    // session-end is now emitted via hf_emit_session_end which takes a code
    // parameter. The bound variable name in the helper is `$code`.
    expect(script).toContain(
      'statusline session-end --host-cli "$HIVE_FLOW_HOSTCLI" --pid "$HIVE_FLOW_PID" --exit-code "$code"',
    );
  });

  it('all session-event calls are best-effort (|| true with stderr suppressed)', () => {
    const script = renderPosixWrapper(baseOpts);
    // Every session-event call must end with `2>/dev/null || true` so a
    // missing or crashing hive-flow CLI cannot abort the wrapper.
    const sessionEventLines = script
      .split('\n')
      .filter((l) => l.includes('statusline session-'));
    expect(sessionEventLines.length).toBeGreaterThanOrEqual(3);
    for (const line of sessionEventLines) {
      expect(line).toContain('2>/dev/null');
      expect(line).toContain('|| true');
    }
  });

  it('validates heartbeat env via a positive-integer regex', () => {
    const script = renderPosixWrapper(baseOpts);
    // Anti-fork-bomb: only `^[1-9][0-9]*$` is accepted. `0`, negatives, and
    // non-numeric strings collapse to the default. We assert the literal
    // regex appears in the rendered script.
    expect(script).toContain("grep -E '^[1-9][0-9]*$'");
  });

  it('rendered default heartbeat is 5 seconds', () => {
    const script = renderPosixWrapper(baseOpts);
    // Default fallback used in both the bash assignment AND the post-pipe
    // `|| echo 5` should match the rendered constant.
    expect(script).toMatch(/HIVE_FLOW_HEARTBEAT_SECONDS:-5/);
    expect(script).toMatch(/\|\| echo 5/);
  });

  it('honors HIVE_FLOW_HEARTBEAT_SECONDS env override at render time', () => {
    const script = renderPosixWrapper({
      ...baseOpts,
      env: { HIVE_FLOW_HEARTBEAT_SECONDS: '10' },
    });
    expect(script).toMatch(/HIVE_FLOW_HEARTBEAT_SECONDS:-10/);
    expect(script).toMatch(/\|\| echo 10/);
  });

  it('rejects invalid HIVE_FLOW_HEARTBEAT_SECONDS at render time (NaN -> 5)', () => {
    const script = renderPosixWrapper({
      ...baseOpts,
      env: { HIVE_FLOW_HEARTBEAT_SECONDS: 'NaN' },
    });
    expect(script).toMatch(/HIVE_FLOW_HEARTBEAT_SECONDS:-5/);
  });

  it('rejects zero HIVE_FLOW_HEARTBEAT_SECONDS at render time (0 -> 5)', () => {
    const script = renderPosixWrapper({
      ...baseOpts,
      env: { HIVE_FLOW_HEARTBEAT_SECONDS: '0' },
    });
    expect(script).toMatch(/HIVE_FLOW_HEARTBEAT_SECONDS:-5/);
  });

  it('rejects negative HIVE_FLOW_HEARTBEAT_SECONDS at render time (-1 -> 5)', () => {
    const script = renderPosixWrapper({
      ...baseOpts,
      env: { HIVE_FLOW_HEARTBEAT_SECONDS: '-1' },
    });
    expect(script).toMatch(/HIVE_FLOW_HEARTBEAT_SECONDS:-5/);
  });

  it('rendered default kill-grace is 1 second', () => {
    const script = renderPosixWrapper(baseOpts);
    expect(script).toMatch(/HIVE_FLOW_KILL_GRACE_SECONDS:-1/);
    expect(script).toMatch(/\|\| echo 1\b/);
  });

  it('honors HIVE_FLOW_KILL_GRACE_SECONDS env override at render time', () => {
    const script = renderPosixWrapper({
      ...baseOpts,
      env: { HIVE_FLOW_KILL_GRACE_SECONDS: '3' },
    });
    expect(script).toMatch(/HIVE_FLOW_KILL_GRACE_SECONDS:-3/);
    expect(script).toMatch(/\|\| echo 3\b/);
  });

  it('rejects invalid HIVE_FLOW_KILL_GRACE_SECONDS at render time (NaN -> 1)', () => {
    const script = renderPosixWrapper({
      ...baseOpts,
      env: { HIVE_FLOW_KILL_GRACE_SECONDS: 'bad' },
    });
    expect(script).toMatch(/HIVE_FLOW_KILL_GRACE_SECONDS:-1/);
  });

  it('renders bounded-grace kill pattern in POSIX script (Wave 11A.7 audit)', () => {
    const script = renderPosixWrapper(baseOpts);
    const sourceOnly = script
      .split('\n')
      .filter((line) => !line.trimStart().startsWith('#'))
      .join('\n');
    expect(sourceOnly).toContain('kill -KILL "$HIVE_FLOW_CHILD_PID"');
    expect(sourceOnly).toContain('kill -0 "$HIVE_FLOW_CHILD_PID"');
    expect(sourceOnly).toContain('HIVE_FLOW_KILL_GRACE_SECONDS');
    expect(sourceOnly).toContain('sleep 0.2');
  });

  it('runs the real CLI as a BACKGROUND child and waits (Wave 11A.6)', () => {
    const script = renderPosixWrapper(baseOpts);
    // Wave 11A.6: the real CLI is launched in the background so INT/TERM
    // traps fire promptly. We assert the `&` backgrounding form and the
    // subsequent `wait` on the child PID. Strip comments before matching
    // so docstring references do not produce false positives.
    const sourceOnly = script
      .split('\n')
      .filter((line) => !line.trimStart().startsWith('#'))
      .join('\n');
    expect(sourceOnly).toContain('"$HIVE_FLOW_REAL_CLI" "$@" &');
    expect(sourceOnly).toContain('HIVE_FLOW_CHILD_PID=$!');
    expect(sourceOnly).toContain('wait "$HIVE_FLOW_CHILD_PID"');
    expect(script).toContain('HIVE_FLOW_EXIT=$?');
    expect(script).toContain('exit "$HIVE_FLOW_EXIT"');
  });

  it('does NOT use `exec` to launch the real CLI (regression guard)', () => {
    // Bug pattern from the Wave 11 audit: any line that uses `exec` to
    // invoke the real CLI binary replaces the wrapper shell and prevents
    // the trap-driven session-end from ever firing. We grep the rendered
    // script for that exact pattern and assert zero hits.
    const script = renderPosixWrapper(baseOpts);
    const execHits = script
      .split('\n')
      .filter((line) => {
        const trimmed = line.trimStart();
        // Comments and docstrings are fine; only real source lines matter.
        if (trimmed.startsWith('#')) return false;
        return /\bexec\s+"\$HIVE_FLOW_REAL_CLI"/.test(trimmed);
      });
    expect(execHits).toEqual([]);
  });

  it('emits session-end exactly once (idempotent via HIVE_FLOW_END_EMITTED)', () => {
    const script = renderPosixWrapper(baseOpts);
    // The shared cleanup helper short-circuits if session-end was already
    // emitted, so the INT/TERM trap path and the normal path cannot
    // double-emit when both run (e.g., trap re-fires during shutdown).
    expect(script).toContain('HIVE_FLOW_END_EMITTED=0');
    expect(script).toContain('HIVE_FLOW_END_EMITTED=1');
    expect(script).toContain(
      'if [ "$HIVE_FLOW_END_EMITTED" = "0" ]; then',
    );
  });

  it('starts a background heartbeat loop guarded by `kill -0`', () => {
    const script = renderPosixWrapper(baseOpts);
    expect(script).toContain('while kill -0 "$HIVE_FLOW_PID" 2>/dev/null; do');
    // The loop must run in a backgrounded subshell.
    expect(script).toMatch(/\) &/);
    expect(script).toContain('HIVE_FLOW_HB_PID=$!');
  });

  it('shell-quotes paths with spaces correctly', () => {
    const script = renderPosixWrapper({
      ...baseOpts,
      realCliBin: '/opt/foo bar/cli',
    });
    expect(script).toContain("HIVE_FLOW_REAL_CLI='/opt/foo bar/cli'");
  });

  it('shell-quotes paths with apostrophes correctly (close/escape/reopen)', () => {
    const script = renderPosixWrapper({
      ...baseOpts,
      realCliBin: "/opt/foo's tool/cli",
    });
    // `'/opt/foo'\''s tool/cli'` is the canonical bash-safe encoding.
    expect(script).toContain(
      "HIVE_FLOW_REAL_CLI='/opt/foo'\\''s tool/cli'",
    );
  });

  it('shell-quotes adversarial paths (command-injection attempt is neutralised)', () => {
    const script = renderPosixWrapper({
      ...baseOpts,
      realCliBin: '/opt/x; rm -rf /',
    });
    // The `;` and `rm` must be inside single quotes — never as bare tokens.
    expect(script).toContain("HIVE_FLOW_REAL_CLI='/opt/x; rm -rf /'");
    // Explicit anti-regression: no occurrence of unquoted `rm -rf /`.
    expect(script).not.toMatch(/^\s*rm\s+-rf\s+\//m);
  });

  it('rejects realCliBin containing control bytes (NUL)', () => {
    expect(() =>
      renderPosixWrapper({
        ...baseOpts,
        realCliBin: '/opt/x' + String.fromCharCode(0) + '/cli',
      }),
    ).toThrow(/control characters/i);
  });

  it('rejects realCliBin containing control bytes (LF)', () => {
    expect(() =>
      renderPosixWrapper({
        ...baseOpts,
        realCliBin: '/opt/x\n/cli',
      }),
    ).toThrow(/control characters/i);
  });

  it('rejects realCliBin containing control bytes (CR)', () => {
    expect(() =>
      renderPosixWrapper({
        ...baseOpts,
        realCliBin: '/opt/x\r/cli',
      }),
    ).toThrow(/control characters/i);
  });

  it('rejects relative realCliBin', () => {
    expect(() =>
      renderPosixWrapper({
        ...baseOpts,
        realCliBin: 'codex',
      }),
    ).toThrow(/absolute POSIX path/i);
  });

  it('rejects empty realCliBin', () => {
    expect(() =>
      renderPosixWrapper({
        ...baseOpts,
        realCliBin: '',
      }),
    ).toThrow(/non-empty/i);
  });

  it('rejects relative hiveFlowCli', () => {
    expect(() =>
      renderPosixWrapper({
        ...baseOpts,
        hiveFlowCli: 'hive-flow',
      }),
    ).toThrow(/absolute POSIX path/i);
  });

  it('rejects invalid hostCli', () => {
    expect(() =>
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      renderPosixWrapper({ ...baseOpts, hostCli: 'not-a-real-cli' as any }),
    ).toThrow(/HostCli/);
  });

  it('accepts every valid HostCli union member', () => {
    const valid = [
      'claude-code',
      'codex',
      'gemini',
      'forgecode',
      'cursor-cli',
      'qwen',
      'opencode',
      'hive-flow-daemon',
      'wrapper',
    ] as const;
    for (const h of valid) {
      expect(() =>
        renderPosixWrapper({ ...baseOpts, hostCli: h }),
      ).not.toThrow();
    }
  });
});

// ---------------------------------------------------------------------------
// renderWindowsWrapper
// ---------------------------------------------------------------------------

describe('renderWindowsWrapper', () => {
  const baseOpts = {
    realCliBin: 'C:\\Program Files\\Codex\\codex.exe',
    hostCli: 'codex' as const,
    hiveFlowCli: 'C:\\Users\\dev\\hive-flow\\bin\\cli.js',
  };

  it('starts with @ECHO OFF and includes AUTO-GENERATED marker', () => {
    const script = renderWindowsWrapper(baseOpts);
    expect(script.startsWith('@ECHO OFF')).toBe(true);
    expect(script).toContain('AUTO-GENERATED by hive-flow wrapper-driver');
  });

  it('uses CRLF line endings', () => {
    const script = renderWindowsWrapper(baseOpts);
    expect(script).toContain('\r\n');
    // No bare LF lines.
    const lines = script.split('\r\n');
    for (const line of lines) {
      expect(line).not.toContain('\n');
    }
  });

  it('dispatches via Node-based wrapper-host subcommand', () => {
    const script = renderWindowsWrapper(baseOpts);
    expect(script).toContain('node ');
    expect(script).toContain('statusline wrapper-host');
  });

  it('passes hostCli, hiveFlowCli, and realCliBin in correct order', () => {
    const script = renderWindowsWrapper(baseOpts);
    // The actual content uses single backslashes (Windows path separator);
    // the regex needs single `\\` to match one backslash literal.
    expect(script).toMatch(
      /node "C:\\Users\\dev\\hive-flow\\bin\\cli\.js" statusline wrapper-host "codex" --heartbeat-default \d+ -- "C:\\Program Files\\Codex\\codex\.exe" %\*/,
    );
  });

  it('sets client kind and optional project root before wrapper-host dispatch', () => {
    const script = renderWindowsWrapper({
      ...baseOpts,
      projectRoot: 'C:\\Users\\test\\project-one',
    });
    expect(script).toContain('SET "HIVE_FLOW_CLIENT_KIND=codex"');
    expect(script).toContain('SET "HIVE_FLOW_PROJECT_ROOT=C:\\Users\\test\\project-one"');
  });

  it('omits explicit project root from user-scoped Windows wrappers', () => {
    const script = renderWindowsWrapper(baseOpts);
    expect(script).not.toContain('HIVE_FLOW_PROJECT_ROOT=');
  });

  it('quotes paths with spaces using CMD double-quote convention', () => {
    const script = renderWindowsWrapper({
      ...baseOpts,
      realCliBin: 'C:\\Program Files\\Codex\\codex.exe',
    });
    expect(script).toContain('"C:\\Program Files\\Codex\\codex.exe"');
  });

  it('captures and propagates %ERRORLEVEL%', () => {
    const script = renderWindowsWrapper(baseOpts);
    expect(script).toContain('SET EXITCODE=%ERRORLEVEL%');
    expect(script).toContain('EXIT /B %EXITCODE%');
  });

  it('uses SETLOCAL/ENDLOCAL to isolate env mutations', () => {
    const script = renderWindowsWrapper(baseOpts);
    expect(script).toContain('SETLOCAL');
    expect(script).toContain('ENDLOCAL');
  });

  it('rejects realCliBin containing % (CMD variable expansion)', () => {
    expect(() =>
      renderWindowsWrapper({
        ...baseOpts,
        realCliBin: 'C:\\foo\\%PATH%\\cli.exe',
      }),
    ).toThrow(/%/);
  });

  it('rejects hiveFlowCli containing % (CMD variable expansion)', () => {
    expect(() =>
      renderWindowsWrapper({
        ...baseOpts,
        hiveFlowCli: 'C:\\foo\\%PATH%\\cli.js',
      }),
    ).toThrow(/%/);
  });

  it('rejects control characters (NaN-bypass: cannot smuggle newlines into the CMD)', () => {
    expect(() =>
      renderWindowsWrapper({
        ...baseOpts,
        realCliBin: 'C:\\foo' + String.fromCharCode(0) + '\\cli.exe',
      }),
    ).toThrow(/control characters/i);
  });

  it('renders heartbeat default flag (Number.isFinite + >= 1 validated downstream)', () => {
    const script = renderWindowsWrapper(baseOpts);
    expect(script).toContain('--heartbeat-default 5');
  });

  it('honors HIVE_FLOW_HEARTBEAT_SECONDS env override at render time', () => {
    const script = renderWindowsWrapper({
      ...baseOpts,
      env: { HIVE_FLOW_HEARTBEAT_SECONDS: '12' },
    });
    expect(script).toContain('--heartbeat-default 12');
  });

  it('rejects invalid HIVE_FLOW_HEARTBEAT_SECONDS at render time (NaN -> 5)', () => {
    const script = renderWindowsWrapper({
      ...baseOpts,
      env: { HIVE_FLOW_HEARTBEAT_SECONDS: 'NaN' },
    });
    expect(script).toContain('--heartbeat-default 5');
  });

  it('rejects zero / negative HIVE_FLOW_HEARTBEAT_SECONDS (Wave 7.5 fork-bomb hardening)', () => {
    const zero = renderWindowsWrapper({
      ...baseOpts,
      env: { HIVE_FLOW_HEARTBEAT_SECONDS: '0' },
    });
    expect(zero).toContain('--heartbeat-default 5');
    const neg = renderWindowsWrapper({
      ...baseOpts,
      env: { HIVE_FLOW_HEARTBEAT_SECONDS: '-3' },
    });
    expect(neg).toContain('--heartbeat-default 5');
  });

  it('rejects invalid hostCli', () => {
    expect(() =>
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      renderWindowsWrapper({ ...baseOpts, hostCli: 'unknown-cli' as any }),
    ).toThrow(/HostCli/);
  });
});

// ---------------------------------------------------------------------------
// writeWrapper
// ---------------------------------------------------------------------------

describe('writeWrapper', () => {
  const baseOpts = {
    realCliBin: '/opt/codex/bin/codex',
    hostCli: 'codex' as const,
    hiveFlowCli: '/usr/local/bin/hive-flow',
  };

  it('writes the wrapper file to destPath under baseDir', async () => {
    const baseDir = dir;
    const destPath = join(baseDir, 'wrappers', 'codex');
    await writeWrapper({ ...baseOpts, destPath, baseDir });
    expect(existsSync(destPath)).toBe(true);
  });

  it('written script content matches renderPosixWrapper on POSIX', async () => {
    if (platform() === 'win32') return; // Windows uses a different template.
    const baseDir = dir;
    const destPath = join(baseDir, 'wrappers', 'codex');
    await writeWrapper({ ...baseOpts, destPath, baseDir });
    const written = await readFile(destPath, 'utf8');
    const expected = renderPosixWrapper(baseOpts);
    expect(written).toBe(expected);
  });

  it('written file has 0o755 mode on POSIX', async () => {
    if (platform() === 'win32') return; // chmod semantics differ.
    const baseDir = dir;
    const destPath = join(baseDir, 'wrappers', 'codex');
    await writeWrapper({ ...baseOpts, destPath, baseDir });
    const st = await stat(destPath);
    // 0o755 = rwxr-xr-x. Mask to the permission bits.
    expect(st.mode & 0o777).toBe(0o755);
  });

  it('creates missing parent directories (single-segment mkdir per Wave 8.4)', async () => {
    const baseDir = dir;
    const destPath = join(baseDir, 'a', 'b', 'c', 'wrapper');
    await writeWrapper({ ...baseOpts, destPath, baseDir });
    expect(existsSync(destPath)).toBe(true);
  });

  it('rejects symlinked parent path (Wave 8.4 ensureSafeUserCacheDir guard)', async () => {
    if (platform() === 'win32') return; // symlink semantics differ.
    const baseDir = dir;
    // Create an "outside" target and link `<baseDir>/wrappers` to it.
    const outside = join(dir, 'outside');
    await mkdir(outside, { recursive: true });
    await symlink(outside, join(baseDir, 'wrappers'));
    // Re-mkdtemp `baseDir` so the link IS within `baseDir`. Actually, we
    // need the baseDir to be a CLEAN ancestor. Use a sibling layout:
    const cleanBase = join(dir, 'clean');
    await mkdir(cleanBase);
    const outsideTwo = join(dir, 'outside2');
    await mkdir(outsideTwo, { recursive: true });
    await symlink(outsideTwo, join(cleanBase, 'wrappers'));
    // Now ensureSafeUserCacheDir(cleanBase/wrappers, cleanBase) must reject:
    // `cleanBase/wrappers` is a symbolic link.
    const destPath = join(cleanBase, 'wrappers', 'codex');
    await expect(
      writeWrapper({ ...baseOpts, destPath, baseDir: cleanBase }),
    ).rejects.toThrow();
    // Verify the link still points outside (write was not followed).
    const linkStat = await lstat(join(cleanBase, 'wrappers'));
    expect(linkStat.isSymbolicLink()).toBe(true);
  });

  it('rejects destPath that escapes baseDir', async () => {
    const baseDir = join(dir, 'inside');
    await mkdir(baseDir, { recursive: true });
    const destPath = join(dir, 'outside', 'wrapper');
    await expect(
      writeWrapper({ ...baseOpts, destPath, baseDir }),
    ).rejects.toThrow();
  });

  it('rejects empty destPath', async () => {
    await expect(
      writeWrapper({ ...baseOpts, destPath: '', baseDir: dir }),
    ).rejects.toThrow(/destPath/);
  });

  it('rejects empty baseDir', async () => {
    await expect(
      writeWrapper({
        ...baseOpts,
        destPath: join(dir, 'wrapper'),
        baseDir: '',
      }),
    ).rejects.toThrow(/baseDir/);
  });

  it('idempotent re-write (same content)', async () => {
    const baseDir = dir;
    const destPath = join(baseDir, 'wrappers', 'codex');
    await writeWrapper({ ...baseOpts, destPath, baseDir });
    await writeWrapper({ ...baseOpts, destPath, baseDir });
    expect(existsSync(destPath)).toBe(true);
    const written = await readFile(destPath, 'utf8');
    // Body still contains the canonical structure.
    expect(written).toContain('AUTO-GENERATED');
  });

  it('round-trip on adversarial realCliBin (spaces + apostrophes + semicolons)', async () => {
    if (platform() === 'win32') return; // POSIX-only adversarial path test.
    const baseDir = dir;
    const destPath = join(baseDir, 'wrappers', 'codex');
    const realCliBin = "/opt/'evil; rm -rf /'/cli";
    await writeWrapper({
      realCliBin,
      hostCli: 'codex',
      hiveFlowCli: '/usr/local/bin/hive-flow',
      destPath,
      baseDir,
    });
    const written = await readFile(destPath, 'utf8');
    // The adversarial path must appear as a literal single-quoted string,
    // never as raw shell tokens.
    expect(written).toContain(
      "HIVE_FLOW_REAL_CLI='/opt/'\\''evil; rm -rf /'\\''/cli'",
    );
    // Defence in depth: no occurrence of bare `rm -rf /` at start of a line.
    expect(written).not.toMatch(/^\s*rm\s+-rf\s+\//m);
  });
});

// ---------------------------------------------------------------------------
// POSIX runtime behaviour (Wave 11 session-end fix).
//
// The previous template used `exec "$HIVE_FLOW_REAL_CLI" "$@"` which replaced
// the wrapper shell with the real CLI. The EXIT trap installed earlier in the
// script could not fire on the now-defunct shell process, so session-end was
// never emitted on normal exit. These tests execute the rendered script
// against a fake real CLI and a fake hive-flow recorder that appends to a
// log file, then assert the expected event sequence and exit code semantics.
// ---------------------------------------------------------------------------

const POSIX_RUNTIME_SKIP = platform() === 'win32';

interface RuntimeFixture {
  readonly wrapperPath: string;
  readonly eventLog: string;
  readonly realCliPath: string;
  readonly hiveFlowCliPath: string;
}

async function makePosixRuntimeFixture(baseDir: string, opts: {
  realCliExitCode?: number;
  realCliSleepSeconds?: number;
} = {}): Promise<RuntimeFixture> {
  const eventLog = join(baseDir, 'events.log');
  // Fake real CLI: exits with the requested code after an optional sleep.
  // The sleep is used by signal tests so we can SIGTERM the wrapper while
  // the child is still running.
  const realCliPath = join(baseDir, 'fake-cli');
  const exitCode = opts.realCliExitCode ?? 0;
  const sleepSeconds = opts.realCliSleepSeconds ?? 0;
  const realCliBody = [
    '#!/usr/bin/env bash',
    'echo "fake-cli args: $*"',
    sleepSeconds > 0 ? `sleep ${sleepSeconds}` : '',
    `exit ${exitCode}`,
    '',
  ].join('\n');
  await writeFile(realCliPath, realCliBody, { mode: 0o755 });
  await chmod(realCliPath, 0o755);

  // Fake hive-flow CLI: appends a JSON-ish line per invocation to the event
  // log. We only care about: which event, which exit-code, which host-cli.
  // The wrapper passes `statusline <subcommand>` as args, so we parse $1=
  // 'statusline', $2 = event name, plus subsequent flag args.
  const hiveFlowCliPath = join(baseDir, 'fake-hive-flow');
  const hiveFlowBody = [
    '#!/usr/bin/env bash',
    `LOG=${JSON.stringify(eventLog)}`,
    '# Args: statusline <event> --host-cli <X> --pid <N> [--exit-code <C>]',
    'EVENT=""',
    'HOSTCLI=""',
    'PIDVAL=""',
    'EXITCODE=""',
    'shift # consume "statusline"',
    'EVENT="$1"',
    'shift',
    'while [ $# -gt 0 ]; do',
    '  case "$1" in',
    '    --host-cli) HOSTCLI="$2"; shift 2 ;;',
    '    --pid) PIDVAL="$2"; shift 2 ;;',
    '    --exit-code) EXITCODE="$2"; shift 2 ;;',
    '    *) shift ;;',
    '  esac',
    'done',
    'printf "event=%s host=%s pid=%s exit=%s\\n" "$EVENT" "$HOSTCLI" "$PIDVAL" "$EXITCODE" >> "$LOG"',
    '',
  ].join('\n');
  await writeFile(hiveFlowCliPath, hiveFlowBody, { mode: 0o755 });
  await chmod(hiveFlowCliPath, 0o755);

  // Render the POSIX wrapper. Heartbeat default = 1 second so heartbeats may
  // (but need not) fire before the child returns.
  const wrapperPath = join(baseDir, 'wrapper');
  const script = renderPosixWrapper({
    realCliBin: realCliPath,
    hostCli: 'codex',
    hiveFlowCli: hiveFlowCliPath,
    env: { HIVE_FLOW_HEARTBEAT_SECONDS: '1' },
  });
  await writeFile(wrapperPath, script, { mode: 0o755 });
  await chmod(wrapperPath, 0o755);

  return { wrapperPath, eventLog, realCliPath, hiveFlowCliPath };
}

describe('renderPosixWrapper runtime behaviour', () => {
  it('emits session-start and session-end when the real CLI exits 0', async () => {
    if (POSIX_RUNTIME_SKIP) return;
    const fx = await makePosixRuntimeFixture(dir, { realCliExitCode: 0 });
    const r = spawnSync('bash', [fx.wrapperPath, 'an-arg'], {
      encoding: 'utf8',
      timeout: 10_000,
    });
    expect(r.status).toBe(0);
    expect(r.stdout).toContain('fake-cli args: an-arg');

    const log = readFileSync(fx.eventLog, 'utf8');
    expect(log).toMatch(/event=session-start host=codex/);
    // session-end must be emitted with the real CLI's exit code (0 here).
    expect(log).toMatch(/event=session-end host=codex pid=\d+ exit=0/);
  });

  it('preserves real CLI exit code 7 in both wrapper exit and session-end', async () => {
    if (POSIX_RUNTIME_SKIP) return;
    const fx = await makePosixRuntimeFixture(dir, { realCliExitCode: 7 });
    const r = spawnSync('bash', [fx.wrapperPath], {
      encoding: 'utf8',
      timeout: 10_000,
    });
    expect(r.status).toBe(7);

    const log = readFileSync(fx.eventLog, 'utf8');
    expect(log).toMatch(/event=session-end host=codex pid=\d+ exit=7/);
  });

  it('preserves real CLI exit code 42 (non-trivial nonzero)', async () => {
    if (POSIX_RUNTIME_SKIP) return;
    const fx = await makePosixRuntimeFixture(dir, { realCliExitCode: 42 });
    const r = spawnSync('bash', [fx.wrapperPath], {
      encoding: 'utf8',
      timeout: 10_000,
    });
    expect(r.status).toBe(42);

    const log = readFileSync(fx.eventLog, 'utf8');
    expect(log).toMatch(/event=session-end host=codex pid=\d+ exit=42/);
  });

  it('emits session-end with 128+SIGTERM=143 when SIGTERM is delivered (Wave 11A.6 regression)', async () => {
    if (POSIX_RUNTIME_SKIP) return;
    // The fake CLI sleeps 8 seconds — long enough that natural exit cannot
    // complete inside the 1500ms prompt-exit deadline. This directly catches
    // the Codex-found bug where a foreground child deferred the TERM trap.
    const fx = await makePosixRuntimeFixture(dir, {
      realCliExitCode: 0,
      realCliSleepSeconds: 8,
    });
    const child = spawn('bash', [fx.wrapperPath], {
      stdio: ['ignore', 'pipe', 'pipe'],
    });
    // Give the wrapper enough time to install traps and start the background child.
    await new Promise<void>((res) => setTimeout(res, 600));

    const signalSentAt = Date.now();
    child.kill('SIGTERM');

    const exitCode: number = await new Promise((res) => {
      child.on('exit', (code, signal) => {
        if (typeof code === 'number') return res(code);
        if (signal === 'SIGTERM') return res(143);
        return res(-1);
      });
    });
    const elapsedMs = Date.now() - signalSentAt;

    expect(exitCode).toBe(143);
    // Wrapper must exit promptly — well within 1500ms of receiving SIGTERM.
    expect(elapsedMs).toBeLessThan(1500);

    // The trap path must have emitted session-end with exit=143 exactly once.
    const log = readFileSync(fx.eventLog, 'utf8');
    const sessionEndMatches = log.match(/event=session-end host=codex pid=\d+ exit=143/g);
    expect(sessionEndMatches).not.toBeNull();
    expect(sessionEndMatches!.length).toBe(1);
  }, 15_000);

  it('emits session-end with 128+SIGINT=130 when SIGINT is delivered (Wave 11A.6)', async () => {
    if (POSIX_RUNTIME_SKIP) return;
    // bash 3.2 (macOS stock) does not deliver the INT trap to a non-interactive
    // script while `wait` is blocking on a background child — the trap is
    // deferred until the child exits naturally. bash 4+ fixed this. Skip on
    // bash 3.x so the test suite passes on macOS without requiring homebrew bash.
    const bashVersionOut = spawnSync('bash', ['--version'], { encoding: 'utf8' });
    const bashVerMatch = bashVersionOut.stdout.match(/version (\d+)\./);
    const bashMajor = bashVerMatch ? parseInt(bashVerMatch[1], 10) : 5;
    if (bashMajor < 4) return;

    // Mirror of the SIGTERM test but for SIGINT -> exit 130.
    const fx = await makePosixRuntimeFixture(dir, {
      realCliExitCode: 0,
      realCliSleepSeconds: 8,
    });
    const child = spawn('bash', [fx.wrapperPath], {
      stdio: ['ignore', 'pipe', 'pipe'],
    });
    await new Promise<void>((res) => setTimeout(res, 600));

    const signalSentAt = Date.now();
    child.kill('SIGINT');

    const exitCode: number = await new Promise((res) => {
      child.on('exit', (code, signal) => {
        if (typeof code === 'number') return res(code);
        if (signal === 'SIGINT') return res(130);
        return res(-1);
      });
    });
    const elapsedMs = Date.now() - signalSentAt;

    expect(exitCode).toBe(130);
    expect(elapsedMs).toBeLessThan(1500);

    const log = readFileSync(fx.eventLog, 'utf8');
    const sessionEndMatches = log.match(/event=session-end host=codex pid=\d+ exit=130/g);
    expect(sessionEndMatches).not.toBeNull();
    expect(sessionEndMatches!.length).toBe(1);
  }, 15_000);

  it('exits promptly with 143 and kills signal-trapping child (Wave 11A.7 regression)', async () => {
    if (POSIX_RUNTIME_SKIP) return;
    // This is the critical gate-7 regression. The fake real CLI TRAPS TERM/INT
    // and then sleeps 10 seconds (simulating slow cleanup) while waiting on
    // its own background child. A wrapper using unbounded `wait` would block
    // for the entire 10-second cleanup. The bounded-grace SIGKILL fallback
    // must force-kill the child within ~1s and allow the wrapper to exit.
    const trapCliPath = join(dir, 'fake-trapping-cli');
    const trapCliPidFile = join(dir, 'fake-trapping-cli.pid');
    const trapCliInnerPidFile = join(dir, 'fake-trapping-cli-inner.pid');
    const trapCliBody = [
      '#!/usr/bin/env bash',
      `echo $$ > ${JSON.stringify(trapCliPidFile)}`,
      "trap 'echo trapped > /dev/null; sleep 10; exit 143' TERM",
      "trap 'echo trapped > /dev/null; sleep 10; exit 130' INT",
      'sleep 100 &',
      'HIVE_INNER_PID=$!',
      `echo $HIVE_INNER_PID > ${JSON.stringify(trapCliInnerPidFile)}`,
      'wait "$HIVE_INNER_PID"',
      '',
    ].join('\n');
    const { writeFile: wf, chmod: ch } = await import('node:fs/promises');
    await wf(trapCliPath, trapCliBody, { mode: 0o755 });
    await ch(trapCliPath, 0o755);

    const eventLog = join(dir, 'trapping-events.log');
    const hiveFlowCliPath = join(dir, 'fake-hive-flow-trapping');
    const hiveFlowBody = [
      '#!/usr/bin/env bash',
      `LOG=${JSON.stringify(eventLog)}`,
      'shift',
      'EVENT="$1"',
      'shift',
      'EXITCODE=""',
      'while [ $# -gt 0 ]; do',
      '  case "$1" in',
      '    --exit-code) EXITCODE="$2"; shift 2 ;;',
      '    *) shift ;;',
      '  esac',
      'done',
      'printf "event=%s exit=%s\\n" "$EVENT" "$EXITCODE" >> "$LOG"',
      '',
    ].join('\n');
    await wf(hiveFlowCliPath, hiveFlowBody, { mode: 0o755 });
    await ch(hiveFlowCliPath, 0o755);

    const wrapperPath = join(dir, 'trapping-wrapper');
    const script = renderPosixWrapper({
      realCliBin: trapCliPath,
      hostCli: 'codex',
      hiveFlowCli: hiveFlowCliPath,
      env: { HIVE_FLOW_HEARTBEAT_SECONDS: '1', HIVE_FLOW_KILL_GRACE_SECONDS: '1' },
    });
    await wf(wrapperPath, script, { mode: 0o755 });
    await ch(wrapperPath, 0o755);

    const child = spawn('bash', [wrapperPath], {
      stdio: ['ignore', 'pipe', 'pipe'],
    });
    // Capture the child PID of the fake-trapping-cli (the "real CLI" spawned by wrapper).
    // We'll check liveness after the wrapper exits.
    const childPid = child.pid!;

    await waitForPidFiles(trapCliPidFile, trapCliInnerPidFile);

    const fakeCliPid = parseInt(readFileSync(trapCliPidFile, 'utf8').trim(), 10);
    const fakeInnerPid = parseInt(readFileSync(trapCliInnerPidFile, 'utf8').trim(), 10);
    expect(Number.isInteger(fakeCliPid) && fakeCliPid > 0).toBe(true);
    expect(Number.isInteger(fakeInnerPid) && fakeInnerPid > 0).toBe(true);

    const signalSentAt = Date.now();
    child.kill('SIGTERM');

    const exitCode: number = await new Promise((res) => {
      child.on('exit', (code, signal) => {
        if (typeof code === 'number') return res(code);
        if (signal === 'SIGTERM') return res(143);
        return res(-1);
      });
    });
    const elapsedMs = Date.now() - signalSentAt;

    // Wrapper must exit 143 within 1500ms (the prompt-exit window).
    expect(exitCode).toBe(143);
    expect(elapsedMs).toBeLessThan(1500);

    // session-end with exit=143 must be emitted exactly once.
    const log = readFileSync(eventLog, 'utf8');
    const sessionEndMatches = log.match(/event=session-end exit=143/g);
    expect(sessionEndMatches).not.toBeNull();
    expect(sessionEndMatches!.length).toBe(1);

    // Gate #7 (runbook line 185): the fake real CLI must NOT be alive after the
    // wrapper's prompt-exit window. The bounded-grace SIGKILL fallback should have
    // force-killed it before its own 10-second cleanup trap finished. We poll for
    // up to 500ms after wrapper exit to allow signal delivery to the orphaned
    // grand-child to settle, then assert it is gone.
    let fakeCliAlive = true;
    let fakeInnerAlive = true;
    const liveCheckDeadline = Date.now() + 500;
    while (Date.now() < liveCheckDeadline) {
      fakeCliAlive = pidIsAlive(fakeCliPid);
      fakeInnerAlive = pidIsAlive(fakeInnerPid);
      if (!fakeCliAlive && !fakeInnerAlive) break;
      await new Promise<void>((res) => setTimeout(res, 50));
    }
    expect(fakeCliAlive).toBe(false);
    expect(fakeInnerAlive).toBe(false);
  }, 20_000);

  it('normal exit does NOT produce exit code 143 (signal trap does not bleed into normal path)', async () => {
    if (POSIX_RUNTIME_SKIP) return;
    // Regression guard: verifies that the TERM trap's exit 143 cannot bleed
    // into the normal-exit path when the child exits on its own (exit 7).
    const fx = await makePosixRuntimeFixture(dir, { realCliExitCode: 7 });
    const r = spawnSync('bash', [fx.wrapperPath], {
      encoding: 'utf8',
      timeout: 10_000,
    });
    expect(r.status).toBe(7);
    expect(r.status).not.toBe(143);

    const log = readFileSync(fx.eventLog, 'utf8');
    // session-end must carry the real exit code (7), never the signal code.
    expect(log).toMatch(/event=session-end host=codex pid=\d+ exit=7/);
    expect(log).not.toMatch(/exit=143/);
  });

  it('rendered POSIX script contains no `exec "$HIVE_FLOW_REAL_CLI"` and uses background pattern (Wave 11A.6 audit)', async () => {
    if (POSIX_RUNTIME_SKIP) return;
    const fx = await makePosixRuntimeFixture(dir);
    const script = readFileSync(fx.wrapperPath, 'utf8');
    // Strip comments first so docstring references do not produce false positives.
    const sourceOnly = script
      .split('\n')
      .filter((line) => !line.trimStart().startsWith('#'))
      .join('\n');
    // Negative assertion: no exec-based launch.
    expect(sourceOnly).not.toMatch(/\bexec\s+"\$HIVE_FLOW_REAL_CLI"/);
    // Positive assertions: background child pattern must be present.
    expect(sourceOnly).toContain('"$HIVE_FLOW_REAL_CLI" "$@" &');
    expect(sourceOnly).toContain('wait "$HIVE_FLOW_CHILD_PID"');
    // Wave 11A.7 positive assertions: bounded-grace kill path must be present.
    expect(sourceOnly).toContain('kill -KILL "$HIVE_FLOW_CHILD_PID"');
    expect(sourceOnly).toContain('kill -0 "$HIVE_FLOW_CHILD_PID"');
    expect(sourceOnly).toContain('HIVE_FLOW_KILL_GRACE_SECONDS');
    expect(sourceOnly).toContain('sleep 0.2');
  });
});

// ---------------------------------------------------------------------------
// Static source audit. The previous wrapper-driver.ts used an unsafe
// `value as HostCli` cast inside `Set.has`. Wave 11 widens the set to
// `ReadonlySet<string>` so the cast is no longer needed. This test reads
// the source file directly and asserts the legacy cast is gone.
// ---------------------------------------------------------------------------

function stripCommentsAndStrings(ts: string): string {
  // Crude but sufficient for source audit: strip `//` line comments and
  // `/* ... */` block comments so docstring mentions of a banned cast pattern
  // do not produce false positives. We also strip single- and double-quoted
  // string literals because they may contain the cast verbatim inside test
  // fixtures or error messages.
  let out = ts.replace(/\/\*[\s\S]*?\*\//g, '');
  out = out.replace(/(^|\n)\s*\/\/[^\n]*/g, '$1');
  out = out.replace(/"(?:[^"\\\n]|\\.)*"/g, '""');
  out = out.replace(/'(?:[^'\\\n]|\\.)*'/g, "''");
  // template literals: drop the entire content between backticks. JS regex
  // does not support recursive matching so we use a non-greedy match — this
  // is best-effort and acceptable because we don't render code inside
  // template literals in this source file.
  out = out.replace(/`(?:[^`\\]|\\.)*`/g, '``');
  return out;
}

describe('wrapper-driver source audit', () => {
  it('contains no `as HostCli` casts (widened ReadonlySet<string>)', () => {
    const here = dirname(fileURLToPath(import.meta.url));
    const sourcePath = resolve(here, '..', 'wrapper-driver.ts');
    const text = readFileSync(sourcePath, 'utf8');
    const scrubbed = stripCommentsAndStrings(text);
    expect(scrubbed).not.toMatch(/\bas\s+HostCli\b/);
  });

  it('contains no unsafe `as any` casts', () => {
    const here = dirname(fileURLToPath(import.meta.url));
    const sourcePath = resolve(here, '..', 'wrapper-driver.ts');
    const text = readFileSync(sourcePath, 'utf8');
    const scrubbed = stripCommentsAndStrings(text);
    // Allow `as const` and `as <named type>` — only ban `as any`.
    expect(scrubbed).not.toMatch(/\bas\s+any\b/);
  });
});

// ---------------------------------------------------------------------------
// parseKillGraceSeconds unit tests (Wave 11A.7).
//
// Mirrors the fork-bomb defence pattern of the existing heartbeat validation.
// Invalid values (NaN, zero, negative, empty, fractional < 1) must collapse
// to the default (1 second); positive integers pass through; fractionals >= 1
// are floored.
// ---------------------------------------------------------------------------

describe('parseKillGraceSeconds', () => {
  it('returns 1 (default) when env is undefined', () => {
    expect(parseKillGraceSeconds(undefined)).toBe(1);
  });

  it('returns 1 (default) when HIVE_FLOW_KILL_GRACE_SECONDS is empty string', () => {
    expect(parseKillGraceSeconds({ HIVE_FLOW_KILL_GRACE_SECONDS: '' })).toBe(1);
  });

  it('returns 1 (default) when HIVE_FLOW_KILL_GRACE_SECONDS is NaN', () => {
    expect(parseKillGraceSeconds({ HIVE_FLOW_KILL_GRACE_SECONDS: 'NaN' })).toBe(1);
  });

  it('returns 1 (default) when HIVE_FLOW_KILL_GRACE_SECONDS is zero', () => {
    expect(parseKillGraceSeconds({ HIVE_FLOW_KILL_GRACE_SECONDS: '0' })).toBe(1);
  });

  it('returns 1 (default) when HIVE_FLOW_KILL_GRACE_SECONDS is negative', () => {
    expect(parseKillGraceSeconds({ HIVE_FLOW_KILL_GRACE_SECONDS: '-5' })).toBe(1);
  });

  it('returns 1 (default) when HIVE_FLOW_KILL_GRACE_SECONDS is non-numeric', () => {
    expect(parseKillGraceSeconds({ HIVE_FLOW_KILL_GRACE_SECONDS: 'abc' })).toBe(1);
  });

  it('returns 1 (default) when HIVE_FLOW_KILL_GRACE_SECONDS is fractional below 1 (0.5)', () => {
    expect(parseKillGraceSeconds({ HIVE_FLOW_KILL_GRACE_SECONDS: '0.5' })).toBe(1);
  });

  it('passes through a valid positive integer (3)', () => {
    expect(parseKillGraceSeconds({ HIVE_FLOW_KILL_GRACE_SECONDS: '3' })).toBe(3);
  });

  it('passes through a valid positive integer (10)', () => {
    expect(parseKillGraceSeconds({ HIVE_FLOW_KILL_GRACE_SECONDS: '10' })).toBe(10);
  });

  it('floors a fractional value >= 1 (1.9 -> 1)', () => {
    expect(parseKillGraceSeconds({ HIVE_FLOW_KILL_GRACE_SECONDS: '1.9' })).toBe(1);
  });

  it('floors a fractional value >= 1 (2.7 -> 2)', () => {
    expect(parseKillGraceSeconds({ HIVE_FLOW_KILL_GRACE_SECONDS: '2.7' })).toBe(2);
  });

  it('HIVE_FLOW_KILL_GRACE_SECONDS absent from env object falls back to 1', () => {
    expect(parseKillGraceSeconds({})).toBe(1);
  });
});

// ---------------------------------------------------------------------------
// Gate 7 + 8: POSIX signal-trapping child runtime regression
// ---------------------------------------------------------------------------
// Verifies the wrapper exits promptly and emits session-end even when the
// real CLI traps TERM/INT and blocks in its own `wait`.
//
// Gate 8: process-liveness is verified via process.kill(pid, 0), NOT pgrep.
// The fake real CLI writes both its own PID and its inner child PID to files
// so we can assert both are dead after the wrapper exits.

const POSIX_ONLY = platform() === 'darwin' || platform() === 'linux';

function pidIsAlive(pid: number): boolean {
  try {
    process.kill(pid, 0);
    return true;
  } catch {
    return false;
  }
}

async function waitForPidFiles(...paths: string[]): Promise<void> {
  const deadline = Date.now() + 5000;
  while (Date.now() < deadline) {
    if (paths.every((p) => existsSync(p))) return;
    await new Promise((r) => setTimeout(r, 50));
  }
  throw new Error('PID files not created within 5s: ' + paths.filter((p) => !existsSync(p)).join(', '));
}

describe.skipIf(!POSIX_ONLY)('Gate 7: signal-trapping child', () => {
  let testDir: string;
  let eventLog: string;
  let fakeHiveFlow: string;
  let fakeRealCli: string;
  let wrapperPath: string;
  let cliPidFile: string;
  let innerPidFile: string;

  beforeEach(async () => {
    testDir = await mkdtemp(join(tmpdir(), 'hf-gate7-'));
    eventLog = join(testDir, 'events.log');
    fakeHiveFlow = join(testDir, 'fake-hive-flow');
    fakeRealCli = join(testDir, 'fake-real-cli');
    wrapperPath = join(testDir, 'wrapper.sh');
    cliPidFile = join(testDir, 'cli.pid');
    innerPidFile = join(testDir, 'inner.pid');

    // Fake hive-flow CLI: records session events to a log file.
    await writeFile(
      fakeHiveFlow,
      [
        '#!/usr/bin/env bash',
        'cmd="${2:-}"',
        'case "$cmd" in',
        '  session-start) echo "session-start" >> ' + JSON.stringify(eventLog) + ' ;;',
        '  session-end)',
        '    ec=""',
        '    for a in "$@"; do',
        '      case "$a" in --exit-code) shift ;; *)',
        '        case "${prev:-}" in --exit-code) ec="$a" ;; esac',
        '      ;; esac; prev="$a"',
        '    done',
        '    echo "session-end code=$ec" >> ' + JSON.stringify(eventLog) + ' ;;',
        '  session-heartbeat) : ;;',
        'esac',
      ].join('\n'),
      { mode: 0o755 },
    );

    // Fake real CLI: traps TERM/INT, starts its own inner child, writes
    // both PIDs to files, and waits indefinitely. The wrapper must kill
    // both the CLI and its inner child via process-group escalation.
    await writeFile(
      fakeRealCli,
      [
        '#!/usr/bin/env bash',
        'echo $$ > ' + JSON.stringify(cliPidFile),
        "trap 'wait' TERM INT",
        'sleep 300 &',
        'echo $! > ' + JSON.stringify(innerPidFile),
        'wait',
      ].join('\n'),
      { mode: 0o755 },
    );

    const script = renderPosixWrapper({
      realCliBin: fakeRealCli,
      hostCli: 'codex' as const,
      hiveFlowCli: fakeHiveFlow,
      env: { HIVE_FLOW_KILL_GRACE_SECONDS: '1' },
    });
    await writeFile(wrapperPath, script, { mode: 0o755 });
  });

  it('SIGTERM exits promptly, emits session-end 143, child+inner dead', async () => {
    const wrapper = spawn('bash', [wrapperPath], {
      stdio: 'ignore',
      detached: false,
    });

    await waitForPidFiles(cliPidFile, innerPidFile);
    process.kill(wrapper.pid!, 'SIGTERM');

    const exitCode = await Promise.race([
      new Promise<number | null>((resolve) =>
        wrapper.on('exit', (code, signal) =>
          resolve(signal === 'SIGTERM' ? 143 : code),
        ),
      ),
      new Promise<'timeout'>((resolve) =>
        setTimeout(() => resolve('timeout'), 4000),
      ),
    ]);

    expect(exitCode).not.toBe('timeout');
    expect(exitCode).toBe(143);

    await new Promise((r) => setTimeout(r, 200));

    // session-end must have been emitted exactly once.
    const events = existsSync(eventLog)
      ? readFileSync(eventLog, 'utf8').trim().split('\n')
      : [];
    const endEvents = events.filter((e) => e.startsWith('session-end'));
    expect(endEvents).toHaveLength(1);
    expect(endEvents[0]).toContain('code=143');

    // Gate 8: verify with process.kill(pid, 0), not pgrep.
    const cliPid = parseInt(readFileSync(cliPidFile, 'utf8').trim(), 10);
    const innerPid = parseInt(readFileSync(innerPidFile, 'utf8').trim(), 10);
    expect(pidIsAlive(cliPid)).toBe(false);
    expect(pidIsAlive(innerPid)).toBe(false);
  }, 10_000);

  it('SIGINT exits promptly with code 130, child+inner dead', async () => {
    const wrapper = spawn('bash', [wrapperPath], {
      stdio: 'ignore',
      detached: false,
    });

    await waitForPidFiles(cliPidFile, innerPidFile);
    process.kill(wrapper.pid!, 'SIGINT');

    const exitCode = await Promise.race([
      new Promise<number | null>((resolve) =>
        wrapper.on('exit', (code, signal) =>
          resolve(signal === 'SIGINT' ? 130 : code),
        ),
      ),
      new Promise<'timeout'>((resolve) =>
        setTimeout(() => resolve('timeout'), 4000),
      ),
    ]);

    expect(exitCode).not.toBe('timeout');
    expect(exitCode).toBe(130);

    await new Promise((r) => setTimeout(r, 200));

    const events = existsSync(eventLog)
      ? readFileSync(eventLog, 'utf8').trim().split('\n')
      : [];
    const endEvents = events.filter((e) => e.startsWith('session-end'));
    expect(endEvents).toHaveLength(1);
    expect(endEvents[0]).toContain('code=130');

    const cliPid = parseInt(readFileSync(cliPidFile, 'utf8').trim(), 10);
    const innerPid = parseInt(readFileSync(innerPidFile, 'utf8').trim(), 10);
    expect(pidIsAlive(cliPid)).toBe(false);
    expect(pidIsAlive(innerPid)).toBe(false);
  }, 10_000);
});
